language: java
jdk: oraclejdk8
sudo: false
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn clean install coveralls:report
deploy:
  provider: bintray
  file: descriptor.json
  user:
    secure: drdiWYh7ievI6mYgEaKPV9+76M5EmxaNZsPpZtPv4vkMpX8mXGS4g8YnKkKBYoJYV8QNsBEh/+UI+zQLMUNNNgTDXfhMIZjSFjNIVR9t9T0bpkZWn41h4iKwcXp0vVERkgEWIg4t9F8AhUR5btgqS8AjRy/eX/h1mZ3er8tVw7tkTnlWBr81+5S41+ZFU4w45X+NCzYappgMWQ0lS9O/GnsV4x+EkNhfseHyzMJwgcPlCE13Ormu8OZwBnCyUj7aJeznehz0PqpECqaxXDLk9wQ6D5KeFsByJBdN6FK34zu8Sgr/7r+FJzlelMFKzGHMdXY2HvNMRkdz6vCy1mfNrsfUWrbWm0/przJ1n7AXQ2XAam84g/B2KvH+OtnBlBI0JV3qJfFd9R04hzqKXC38kcTyaMbqbOeQZwZfJJI6Dv+8b2twcaQ/C7wPmsUQ6C6w6PQQasfMqMVvwiOMZS7NCABkZaCb85bzq0hV5T7LoY21M0Pqb2sK3I1OA+KkdK1/pz9YrlE/cB255CMdxTv/60XX2MKvIWcLIt8a2gd9SK4tcu458UUOZKLdjnNgsvOoi4948SuaOcQ1KM7IZk2fhPGLTmJS8hfI29LzAEKlFxPWV+QAXktIEKYlZ48V+pF0A9to98G+XCY2kkZnJwpxa2lXezOy80dnnmIrzpxz2yY=
  key:
    secure: RNiDO4Nyde5dhD5y/Fk1NQBu46TV8TF6ATngHXXbhd+Mt9v1p02/HIBj21dQqTjbtH2aOw/NEc2HHVozvzWEOCcxLMGMNKjyetHUCmD0OAbT7l8xJmAzTIu14jZIAZ8nJxRzZelrTK9OksVABV+/CwhAsEyss5m0THTMaPtK/+8VSkoreVV6cClyLNTG5WfxUhe3CxgxISk19SDMJH83L4/Ii1BNJ4gHJa0uF9wyXgdMDYz9Rd+E0EKPMJ0y2V0fJFjXQEDiJ0yMKK185I6GHMND2Hq2DxVNWUYuGJuMNM6Xuh6akH8TiUk75c5bZDChN6zBaUZqfPSG+r2TC3f9WNTZ292kHtFO/y4f9gaPKLtmW2ewfkqCl6ovx6xUVhboFFhceRKSs9le64O5p85TQq2Hv7d6vBR/gzzf8r1vcRCFcZD+bi+ZtO5JVIdGtnOVdOQyH+Nfgrsxq3kshFht0PMMAqxMuC14KUHb4qGA9mDU+yFP/zktvXCbMRWHOuzSRoLSrnUsXY4w7c3E8RtYqaPRl2ujr2E9drUBzf0wUjzz2lYcLpBRZWfytRLa6bwZwolsAt5jZS5z0ZbINz0BQ8l33iQrAKO/UAE4H3AxTswooYIp/Z31fOQNxIEWednYlCYxlxgxisyqNX6Qbb1UEhIx0sSb8SRRYfJptbA93Xk=
