language: java
jdk:
  - oraclejdk8
sudo: false
script: 
  - wget https://raw.githubusercontent.com/avojak/settings.xml/master/settings.xml -O /tmp/settings.xml
  - mvn clean verify coveralls:report deploy --settings /tmp/settings.xml