language: java
jdk: oraclejdk8
sudo: false
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn install coveralls:report
after_success: 
- wget https://raw.githubusercontent.com/avojak/settings.xml/master/settings.xml -O /tmp/settings.xml
- mvn site deploy site:deploy --settings /tmp/settings.xml