language: java
jdk: oraclejdk8
sudo: false
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn clean install coveralls:report
deploy:
  provider: bintray
  file: descriptor.json
  user: avojak
  key:
    secure: RNiDO4Nyde5dhD5y/Fk1NQBu46TV8TF6ATngHXXbhd+Mt9v1p02/HIBj21dQqTjbtH2aOw/NEc2HHVozvzWEOCcxLMGMNKjyetHUCmD0OAbT7l8xJmAzTIu14jZIAZ8nJxRzZelrTK9OksVABV+/CwhAsEyss5m0THTMaPtK/+8VSkoreVV6cClyLNTG5WfxUhe3CxgxISk19SDMJH83L4/Ii1BNJ4gHJa0uF9wyXgdMDYz9Rd+E0EKPMJ0y2V0fJFjXQEDiJ0yMKK185I6GHMND2Hq2DxVNWUYuGJuMNM6Xuh6akH8TiUk75c5bZDChN6zBaUZqfPSG+r2TC3f9WNTZ292kHtFO/y4f9gaPKLtmW2ewfkqCl6ovx6xUVhboFFhceRKSs9le64O5p85TQq2Hv7d6vBR/gzzf8r1vcRCFcZD+bi+ZtO5JVIdGtnOVdOQyH+Nfgrsxq3kshFht0PMMAqxMuC14KUHb4qGA9mDU+yFP/zktvXCbMRWHOuzSRoLSrnUsXY4w7c3E8RtYqaPRl2ujr2E9drUBzf0wUjzz2lYcLpBRZWfytRLa6bwZwolsAt5jZS5z0ZbINz0BQ8l33iQrAKO/UAE4H3AxTswooYIp/Z31fOQNxIEWednYlCYxlxgxisyqNX6Qbb1UEhIx0sSb8SRRYfJptbA93Xk=
